# Generated by Django 6.1.1 on 2026-09-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Заїзд')),
                ('check_out', models.DateField(verbose_name='Виїзд')),
                ('time_arrival', models.TimeField(default='14:00', verbose_name='Час заїзду')),
                ('time_departure', models.TimeField(default='12:00', verbose_name='Час виїзду')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='Дорослих')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Дітей')),
                ('children_ages', models.JSONField(blank=True, default=list, verbose_name='Вік дітей')),
                ('room_type_id', models.IntegerField(verbose_name='ID типу номера')),
                ('contract_condition_id', models.IntegerField(verbose_name='ID тарифу')),
                ('api_price_list_id', models.IntegerField(verbose_name='ID прайс-листа')),
                ('room_name', models.CharField(max_length=255, verbose_name='Номер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('currency', models.PositiveSmallIntegerField(choices=[(980, 'UAH'), (840, 'USD'), (978, 'EUR')], default=980, verbose_name='Валюта')),
                ('guest_name', models.CharField(max_length=255, verbose_name="Ім'я гостя")),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guest_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('country_of_residence', models.CharField(default='ua', max_length=2, verbose_name='Країна проживання')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('servio_booking_id', models.CharField(blank=True, help_text='apiReservationID з відповіді /book', max_length=64, verbose_name='Номер броні в Servio')),
                ('payment_url', models.URLField(blank=True, max_length=1000, verbose_name='Посилання на оплату')),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('confirmed', 'Підтверджена'), ('failed', 'Відхилена')], default='pending', max_length=16, verbose_name='Статус')),
                ('raw_request', models.JSONField(blank=True, default=dict, verbose_name='Сирий запит')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Сира відповідь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'броні',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='booking_status_idx'), models.Index(fields=['check_in'], name='booking_check_in_idx'), models.Index(fields=['servio_booking_id'], name='booking_servio_id_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_check_out_after_check_in')],
            },
        ),
    ]
