# Generated by Django 6.1.1 on 2026-09-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує оплати'), ('confirmed', 'Підтверджена'), ('failed', 'Відхилена — оплату не вдалося ініціювати'), ('expired', 'Відхилена — час на оплату вийшов')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
