"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    CSRF_TRUSTED_ORIGINS=(list, []),
)

# Local development reads .env; on the server every value comes from the
# environment (docker compose / GitHub Secrets), so a missing file is fine.
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Needed for the admin login form once the app is served on a non-standard
# port (http://<host>:8080) — Django checks Origin against this list.
CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'booking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves STATIC_ROOT straight from gunicorn — no nginx in front of the
    # container. Must sit directly after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Driven entirely by DATABASE_URL: sqlite locally, postgres in the container.
# Keep this the only place the engine is chosen — no PG-only fields in models.
DATABASES = {
    'default': env.db_url(
        'DATABASE_URL',
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
    ),
}

# Persistent connections: worth it behind gunicorn + Postgres, pointless with
# the dev server. Defaults match Django's, so nothing changes until the
# container sets them.
DATABASES['default']['CONN_MAX_AGE'] = env.int('CONN_MAX_AGE', default=0)
DATABASES['default']['CONN_HEALTH_CHECKS'] = env.bool(
    'CONN_HEALTH_CHECKS', default=False,
)


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'uk'

# Stored in UTC (USE_TZ), displayed in hotel local time — the admin is read
# by the hotel, so Kyiv time is what makes sense there.
TIME_ZONE = 'Europe/Kyiv'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compressed, but deliberately NOT the manifest variant: manifest
        # storage hard-fails on a missing manifest, which would break every
        # test run and any `runserver` before collectstatic.
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# Security
# The assignment serves the demo over plain HTTP (http://<ip>:8080), so the
# TLS-only switches stay off — turning them on would break the site rather
# than protect it. They are env-driven so a TLS deployment needs no code change.

SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# This site never sends mail — the hotel's HMS notifies the guest. The backend
# is env-driven anyway so a deployment that needs it can point at SMTP without
# touching code. `check --deploy` reports mail.E001 for anything but SMTP;
# that finding is expected here, see docs/PLAN.md.
MAILERS = {
    'default': {
        'BACKEND': env(
            'EMAIL_BACKEND',
            default='django.core.mail.backends.console.EmailBackend',
        ),
    },
}


# Admin account provisioned by `manage.py ensure_admin` on every deploy.
# The assignment requires admin:demo on the demo site; a real deployment must
# override ADMIN_PASSWORD via the environment.

ADMIN_USERNAME = env('ADMIN_USERNAME', default='admin')
ADMIN_PASSWORD = env('ADMIN_PASSWORD', default='demo')
ADMIN_EMAIL = env('ADMIN_EMAIL', default='')


# HMS Servio integration
# All calls go through the Django backend, never from the browser.

SERVIO_API_BASE = env(
    'SERVIO_API_BASE',
    default='https://smartspot.servio.support/ServioQR/hms/api',
)

# Two different identifiers, both required (see docs/servio-api.md):
#   companyKey — tenant GUID, hotelID — the hotel's internal numeric id.
# Neither is a secret: both are visible in the public booking widget.
SERVIO_COMPANY_KEY = env('SERVIO_COMPANY_KEY', default='')
SERVIO_HOTEL_ID = env.int('SERVIO_HOTEL_ID', default=0)

SERVIO_TIMEOUT = env.float('SERVIO_TIMEOUT', default=15.0)


# Logging
# Every Servio call is logged as key=value (see booking/services/servio.py).
# Without an explicit config those records would be dropped once DEBUG=False,
# which is exactly when we need them.

LOG_LEVEL = env('LOG_LEVEL', default='INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'app': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'app',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'booking': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
